package com.lms.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

@Entity
@Table(name = "interview_questions")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor
public class InterviewQuestion {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @com.fasterxml.jackson.annotation.JsonBackReference
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "interview_id", nullable = false)
    private MockInterview interview;

    /** The question generated by AI */
    @Column(length = 2000, nullable = false)
    private String question;

    /** Hint generated alongside question */
    @Column(length = 1000)
    private String hint;

    /** The user's typed answer */
    @Column(length = 5000)
    private String userAnswer;

    /** Voice-based answer (audio file URL from storage) */
    @Column(length = 500)
    private String voiceAnswerUrl;

    /** Transcribed text from voice answer (for processing) */
    @Column(length = 5000)
    private String voiceTranscription;

    /** Duration of voice answer in seconds */
    private Integer voiceDurationSeconds;

    /** AI-generated ideal answer */
    @Column(length = 5000)
    private String idealAnswer;

    /** AI score for this answer 0-100 */
    private Integer score;

    /** AI feedback for this answer */
    @Column(length = 3000)
    private String feedback;

    /** Strong points noted by AI */
    @Column(length = 1000)
    private String strengths;

    /** Areas to improve noted by AI */
    @Column(length = 1000)
    private String improvements;

    private Integer orderIndex;

    @CreationTimestamp
    private LocalDateTime askedAt;

    private LocalDateTime answeredAt;
}

