-- ╔════════════════════════════════════════════════════════════════════════════════╗
-- ║                                                                                  ║
-- ║                   MOCK INTERVIEW FEATURE - DATABASE SCHEMA                      ║
-- ║                                                                                  ║
-- ║                         LearnHub SaaS LMS Platform                              ║
-- ║                                                                                  ║
-- ╚════════════════════════════════════════════════════════════════════════════════╝

-- ═══════════════════════════════════════════════════════════════════════════════════
-- TABLE: mock_interviews
-- DESCRIPTION: Stores mock interview sessions for users
-- ═══════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS mock_interviews (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,

    -- Foreign Key: Reference to users table
    user_id BIGINT NOT NULL,

    -- Interview Configuration
    topic VARCHAR(255) NOT NULL COMMENT 'e.g., Java, React, System Design, Python, etc.',
    difficulty ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED') NOT NULL DEFAULT 'INTERMEDIATE',
    interview_type ENUM('TEXT', 'VOICE') NOT NULL DEFAULT 'TEXT' COMMENT 'TEXT or VOICE based interview',
    total_questions INT NOT NULL DEFAULT 5,

    -- Interview Status & Tracking
    status ENUM('IN_PROGRESS', 'COMPLETED', 'ABANDONED') NOT NULL DEFAULT 'IN_PROGRESS',

    -- Performance Metrics
    overall_score INT COMMENT 'Final score (0-100) assigned after completion',
    overall_feedback LONGTEXT COMMENT 'AI-generated overall feedback paragraph (up to 4000 chars)',

    -- Timestamps
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL COMMENT 'Set when interview is completed or abandoned',

    -- Indexes for performance
    INDEX idx_user_id (user_id),
    INDEX idx_status (status),
    INDEX idx_started_at (started_at),

    -- Foreign Key Constraint
    CONSTRAINT fk_mock_interviews_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores mock interview sessions and overall performance metrics';

-- ═══════════════════════════════════════════════════════════════════════════════════
-- TABLE: interview_questions
-- DESCRIPTION: Stores individual questions and answers within a mock interview session
-- ═══════════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS interview_questions (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,

    -- Foreign Key: Reference to mock_interviews table
    interview_id BIGINT NOT NULL,

    -- Question Content (Generated by AI)
    question LONGTEXT NOT NULL COMMENT 'The question generated by Gemini AI (up to 2000 chars)',
    hint VARCHAR(1000) COMMENT 'Hint generated alongside the question',
    order_index INT NOT NULL COMMENT 'Question sequence within the interview (1, 2, 3, ...)',

    -- Student Response
    user_answer LONGTEXT COMMENT 'The answer provided by the student (up to 5000 chars)',

    -- Voice-Based Answer Fields
    voice_answer_url VARCHAR(500) COMMENT 'URL/path to uploaded audio file for voice-based answers',
    voice_transcription LONGTEXT COMMENT 'Transcribed text from voice answer (for AI processing)',
    voice_duration_seconds INT COMMENT 'Duration of voice answer in seconds',

    ideal_answer LONGTEXT COMMENT 'AI-generated ideal answer (up to 5000 chars)',
    score INT COMMENT 'AI score for this answer (0-100 scale)',
    feedback LONGTEXT COMMENT 'AI feedback for this answer (up to 3000 chars)',
    strengths VARCHAR(1000) COMMENT 'Strong points noted by AI',
    improvements VARCHAR(1000) COMMENT 'Areas to improve noted by AI',

    -- Timestamps
    asked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When question was presented to student',
    answered_at TIMESTAMP NULL COMMENT 'When student submitted their answer',

    -- Indexes for performance
    INDEX idx_interview_id (interview_id),
    INDEX idx_order_index (order_index),
    INDEX idx_answered_at (answered_at),

    -- Foreign Key Constraint
    CONSTRAINT fk_interview_questions_interview FOREIGN KEY (interview_id)
        REFERENCES mock_interviews(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT='Stores individual questions and AI-generated evaluations for each interview';

-- View to get interview statistics per user
CREATE OR REPLACE VIEW interview_user_stats AS
SELECT
    u.id as user_id,
    u.email,
    COUNT(mi.id) as total_interviews,
    SUM(CASE WHEN mi.status = 'COMPLETED' THEN 1 ELSE 0 END) as completed_interviews,
    SUM(CASE WHEN mi.status = 'ABANDONED' THEN 1 ELSE 0 END) as abandoned_interviews,
    AVG(CASE WHEN mi.status = 'COMPLETED' THEN mi.overall_score ELSE NULL END) as avg_score,
    MAX(mi.started_at) as last_interview_date
FROM users u
LEFT JOIN mock_interviews mi ON u.id = mi.user_id
GROUP BY u.id, u.email;

-- View to get interview performance by topic
CREATE OR REPLACE VIEW interview_topic_stats AS
SELECT
    topic,
    difficulty,
    COUNT(*) as total_attempts,
    AVG(overall_score) as avg_score,
    COUNT(CASE WHEN status = 'COMPLETED' THEN 1 END) as completed_count,
    MIN(overall_score) as min_score,
    MAX(overall_score) as max_score
FROM mock_interviews
WHERE status = 'COMPLETED'
GROUP BY topic, difficulty;

